name: alex_k_test
description: "Test Flutter project for See Tree."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  either_dart: ^1.0.0
  get_it: ^8.0.3
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  logger: ^2.0.0
  connectivity_plus: ^6.1.1
  firebase_core: ^3.8.1
  firebase_database: ^11.2.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  sqflite: ^2.4.1
  shared_preferences: ^2.3.3
  json_annotation: ^4.9.0
  permission_handler: ^11.3.1
  rxdart: ^0.28.0
  geolocator: ^13.0.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_map_tile_caching: ^9.0.1
  path_provider: ^2.1.2

  path: any
  bloc: any
  collection: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/
